repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.52.2
    hooks:
    -   id: golangci-lint
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
    -   id: markdownlint
